#!/usr/bin/env bash

# Check for bucket name
if [ -z "$1" ]; then
    echo "There need to be a bucket name e.g $0 my-bucket-name"
    exit 1
fi
BUCKET_NAME=$1
aws s3api create-bucket \
--bucket $BUCKET_NAME